### ISSUE TITLE
fix some errors, please check and merge PR

### ISSUE THREAD

**Issue by hilerchyn** [iris-contrib/gitbook#3]
hi @kataras , I have read the book of Iris framework,  and found some errors.

the pull requests are:
1. [fix example code errors](https://github.com/iris-contrib/gitbook/pull/2)
2. [remove extra bracket](https://github.com/iris-contrib/gitbook/pull/1)

please check and confirm.

**Comment by ghost** [comment]
Correct, excellent, thanks you!
