### ISSUE TITLE
streaming.md

### ISSUE THREAD

**Issue by ivancduran** [iris-contrib/gitbook#30]
The "streaming.md" file was deleted or changed.
Then the link on the documentation was broken on the next urls:

https://docs.iris-go.com/streaming.md
https://www.gitbook.com/book/kataras/iris/details
https://github.com/iris-contrib/gitbook/blob/master/streaming.md

This isn't really a big issue, but I put this issue here to take the control and not lost into the rocketchat.

Thanks you.

**Comment by ghost** [comment]
You have right, I'll re-implement the streaming right now
